# Generated by Django 4.1.7 on 2023-02-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New_Csv_File', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondetail',
            name='dob',
            field=models.DateField(auto_now=True),
        ),
    ]
