# Generated by Django 4.1.7 on 2023-02-22 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('New_Csv_File', '0004_remove_persondetail_hobby_remove_persondetail_skill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skill_type',
        ),
        migrations.AlterField(
            model_name='persondetail',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='New_Csv_File.country'),
        ),
        migrations.DeleteModel(
            name='SkillCategory',
        ),
    ]
